services:

  redis:
    image: redis:latest
    container_name: redis_fastapi_db
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - 8081:8081
    depends_on:
      - redis

  backend:
    build: inline_backend
    depends_on:
      - redis
    ports:
      - 8000:8000
    volumes:
      - ./inline_backend:/code


volumes:
  redis-data: